# Generated by Django 4.2 on 2025-01-28 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_enrollment_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='remaining_capacity',
        ),
    ]
