# Generated by Django 4.2 on 2025-01-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_course_remaining_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='initial_capacity',
            field=models.IntegerField(default=20),
        ),
    ]
