# Generated by Django 4.2 on 2025-01-29 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_initial_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseClassroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.classroom')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_classroom', to='course.course')),
            ],
        ),
    ]
