# Generated by Django 4.2 on 2025-01-29 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_courseclassroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseclassroom',
            old_name='Classroom',
            new_name='classroom',
        ),
    ]
