# Generated by Django 4.2 on 2025-01-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_student_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='national_id',
            field=models.IntegerField(),
        ),
    ]
